<?php
    $viewTitle = isset($this->viewTitle) ? $this->viewTitle : "";
    $viewDescription = isset($this->viewDescription) ? $this->viewDescription : "";
    $viewImage = isset($this->viewImage) ? $this->viewImage : "";
    $viewKeywords = isset($this->viewKeywords) ? $this->viewKeywords : "";
    $viewCaptcha = isset($this->viewCaptcha) ? $this->viewCaptcha : null;
    $viewAlert = isset($this->viewAlert) ? $this->viewAlert : null;
    
    $viewLink = isset($this->viewLink) ? $this->viewLink : '';
    $viewAnswer = isset($this->viewAnswer) ? $this->viewAnswer : '';
    $viewResult = isset($this->viewResult) ? $this->viewResult : '';
    
    $helper = $this->helper;
    $question = '';
    
    if ($viewCaptcha){
        $question = $helper->getArrayValue($viewCaptcha, 'question');
    }
    
    $baseUrl = \NG\Uri::baseUrl();
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
    <meta name="image" content="<?php echo $viewImage; ?>">
    <meta name="keywords" content="<?php echo $viewKeywords; ?>" />
    <meta name="description" content="<?php echo $viewDescription ?>" />
    <title><?php echo $viewTitle ?></title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="<?php echo $baseUrl ?>assets/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="<?php echo $baseUrl ?>assets/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="<?php echo $baseUrl ?>assets/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="<?php echo $baseUrl ?>assets/css/AdminLTE.min.css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition register-page">
<div class="register-box">
    <div class="register-logo">
        DEL.ONE
    </div>
    <div class="register-box-body">
        <p class="login-box-msg"><strong>Buat tautan singkat</strong></p>
        <?php 
        if ($viewAlert){
            $title = $helper->getArrayValue($viewAlert, 'title');
            $type = $helper->getArrayValue($viewAlert, 'type');
            $message = $helper->getArrayValue($viewAlert, 'message');
        ?>
        <div class="alert alert-<?php echo $type ?> alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h4><i class="icon fa fa-info"></i> <?php echo $title ?></h4>
            <?php echo $message ?>
        </div>
        <?php } ?>
        <form action="" method="post">
            <div class="form-group has-feedback">
                <label for="link">Tautan</label>
                <input type="text" id="link" name="link" class="form-control" placeholder="Tautan" value="<?php echo $viewLink ?>" required>
                <span class="glyphicon glyphicon-console form-control-feedback"></span>
            </div>
            <div class="form-group has-feedback">
                <label for="captcha">Berapakah <?php echo $question ?>?</label>
                <input type="text" id="captcha" name="captcha" class="form-control" placeholder="Captcha" value="<?php echo $viewAnswer ?>" required>
            </div>
            <div class="form-group has-feedback text-center">
                <button type="submit" name="create" id="create" class="btn btn-primary btn-block btn-flat">Buat</button>
            </div>
        </form>
        <?php if ($viewResult){ ?>
            <div class="form-group has-feedback">
                <label for="link" />Hasil</label>
                <input type="text" id="result" name="result" class="form-control" placeholder="Hasil" value="<?php echo $baseUrl . $viewResult ?>" readonly>
            </div>
        <?php } ?>
    </div>
    <!-- /.form-box -->
</div>
<!-- /.register-box -->

<!-- jQuery 3 -->
<script src="<?php echo $baseUrl ?>assets/js/jquery.min.js"></script>
<!-- Bootstrap 3.3.7 -->
<script src="<?php echo $baseUrl ?>assets/js/bootstrap.min.js"></script>
</body>
</html>
